# DigitalOcean Droplet
apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: example-droplet
spec:
  forProvider:
    region: nyc1
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
    backups: false
    ipv6: true
    tags:
      - web
      - production
  writeConnectionSecretToRef:
    name: example-droplet-conn
    namespace: crossplane-system
  providerConfigRef:
    name: digitalocean-provider 